version: '3'

services:
  debian-buster-php:
    tty: true
    restart: always
    build:
      context: ./debian
    ports:
      - ${WEB_PORT}:80
      - ${WEB_SOCKET_PORT}:8080
    volumes:
      - ${APP_PATH}:/app
    env_file:
      - .env
    container_name: amalgam_backend

  maria-db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amalgam
      MYSQL_USER: amalgam
      MYSQL_PASSWORD: amalgam
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MARIADB_STORAGE_FOLDER}:/var/lib/mysql
      - ${MARIADB_EXTRA_ENTRYPOINT}:/docker-entrypoint-initdb.d
    env_file:
      - .env
    container_name: amalgam_mariadb

  memcached:
    restart: always
    image: memcached:alpine
    ports:
      - "11215:11211"
    env_file:
      - .env
    container_name: amalgam_memcached