version: '3'

services:
  debian-buster-php:
    restart: always
    build:
      context: ./debian
    working_dir: /app
    ports:
      - ${WEB_SOCKET_PORT}:8080
    volumes:
      - ${APP_PATH}:/app
    env_file:
      - .env
    container_name: amalgam_backend

  maria-db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amalgam
      MYSQL_USER: amalgam
      MYSQL_PASSWORD: amalgam
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MARIADB_STORAGE_FOLDER}:/var/lib/mysql
      - ${MARIADB_EXTRA_ENTRYPOINT}:/docker-entrypoint-initdb.d
    env_file:
      - .env
    container_name: amalgam_mariadb

  memcached:
    restart: always
    image: memcached:alpine
    ports:
      - "${MEMCACHED_PORT}:11211"
    env_file:
      - .env
    container_name: amalgam_memcached

  node:
    restart: always
    build:
      context: ./node
    working_dir: /app
    volumes:
      - ${APP_FRONT_PATH}:/app
    ports:
      - ${APP_FRONT_PORT}:4545
    env_file:
      - .env
    container_name: amalgam_front
